// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceptvxbkyatsyrpttwbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcHR2eGJreWF0c3lycHR0d2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NjExNDUsImV4cCI6MjA1MDQzNzE0NX0.mB8Gzd-K7pwv7mE_16NMTFoiLF58-dDPU1OJcp10iuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);